### ISSUE TITLE
Issues with footer on mobile devices

### ISSUE THREAD

**Issue by petrk94** [Seravo/wp-simple-header-footer-html#3]
Hello,
Im not sure whether this repo still is maintained, but I hope I get a answer.
I have the plugin in use and put there some html and css content in the footer (html and css separated).
All is working well and on computer I can use the footer functions like clicking a link. But on mobiles it doesnt work. No link in the footer can be clicked.

I hope you can help.
Thanks

**Comment by ottok** [comment]
Yes, this repo is still maintained. I don't think your issue is related to anything that this plugin would do wrong. You simply need check what code you pasted into the areas the plugin provides. It is the responsibility of the user to make sure the insert correct code to their websites via this plugin.

**Comment by petrk94** [comment]
@ottok yes this is definitely true, but I have put it on codepen.io
there the code is working. If I follow the links on codepen.io to the page they are linked, I see the behavior, that the links on the page are not working.

**Comment by petrk94** [comment]
@ottok  there is definitely a issue, but I dont know whether its a plugin or not.
I have removed all linked css and raw css in the field above.

Now there is only the html content

```
<html>
<ul class="social-icons icon-square icon-zoom list-unstyled list-inline"> 
	<h1><a href="https://www.google.com"> Test </a></h1>
	<li>
	<a href="https://www.linkedin.com"><i class="fa fa-linkedin"></i></a>
	</li>   
</ul>
			</div>
		</footer>
</html>
```

And this is only a link, but the link is not clickable, and I have no idea why, on desktop it works, but not on mobile phone.

**Comment by petrk94** [comment]
@ottok Im sorry, I have found the issue.
The issue is not in the plugin, its in the theme which cause on the Plugin this issue.
